rootProject.name = "java-util"
include("annotations")
include("kotlin")
include("agent")
include("all")
include("collection")
include("promise")
include("common")
include("reflector")
include("reflect")
include("serialization")
include("yaml")
include("io")
include("nbs")
include("http")
include("event-emitter")
include("maven")
