/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_memory_MemoryMeasure */

#ifndef _Included_util_memory_MemoryMeasure
#define _Included_util_memory_MemoryMeasure
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_memory_MemoryMeasure
 * Method:    sizeof
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_util_memory_MemoryMeasure_sizeof
  (jobject);

#ifdef __cplusplus
}
#endif
#endif
