dependencies {
    api(project(":annotations"))
    api(project(":collection"))
    api(project(":io"))
    api(project(":kotlin"))
    api(project(":nbs"))
    api(project(":promise"))
    api(project(":reflect"))
    api(project(":reflector"))
    api(project(":serialization"))
    api(project(":yaml"))
    api(project(":event-emitter"))
    api(project(":http"))
    api(project(":maven"))
}
