name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Prepare gradle.properties
        run: |
          mkdir -p $HOME/.gradle
          echo "azisabaUsername=${{ secrets.AZISABA_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "azisabaPassword=${{ secrets.AZISABA_PASSWORD }}" >> $HOME/.gradle/gradle.properties
      - name: Deploy
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: ./gradlew clean test publishToCentral publish
