name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to GitHub Packages with Gradle
      run: ./gradlew -DdeploySnapshotURL=https://maven.pkg.github.com/acrylic-style/java-util -DdeployReleasesURL=https://maven.pkg.github.com/acrylic-style/java-util -DrepoUsername=acrylic-style -DrepoPassword=${{ secrets.GITHUB_TOKEN }} publish
